#!/bin/sh
# Resolve image matrix rows for CI.
# Prints one TSV line per image: name context dockerfile base_name_or_empty

set -eu

emit() {
  name="$1"
  context="$2"
  dockerfile="$3"
  base="${4:-}"
  printf '%s\t%s\t%s\t%s\n' "${name}" "${context}" "${dockerfile}" "${base}"
}

emit "minecraft-base" "dockerized/bases/minecraft" "dockerized/bases/minecraft/Dockerfile" ""
emit "steam-base" "dockerized/bases/steam" "dockerized/bases/steam/Dockerfile" ""
emit "runtime-base" "dockerized/bases/runtime" "dockerized/bases/runtime/Dockerfile" ""

emit "minecraft-fabric" "dockerized/minecraft" "dockerized/minecraft/fabric/Dockerfile" "minecraft-base"
emit "minecraft-vanilla" "dockerized/minecraft" "dockerized/minecraft/vanilla/Dockerfile" "minecraft-base"
emit "minecraft-forge" "dockerized/minecraft" "dockerized/minecraft/forge/Dockerfile" "minecraft-base"
emit "minecraft-neoforge" "dockerized/minecraft" "dockerized/minecraft/neoforge/Dockerfile" "minecraft-base"

emit "valheim" "dockerized/valheim/vanilla" "dockerized/valheim/vanilla/Dockerfile" "steam-base"
emit "valheim-plus" "dockerized/valheim/plus" "dockerized/valheim/plus/Dockerfile" "steam-base"
emit "ground-branch" "dockerized/ground-branch" "dockerized/ground-branch/Dockerfile" "steam-base"
emit "space-engineers" "dockerized/space-engineers" "dockerized/space-engineers/Dockerfile" "steam-base"
emit "core-keeper" "dockerized/core-keeper" "dockerized/core-keeper/Dockerfile" "steam-base"
emit "7-days-to-die" "dockerized/7-days-to-die" "dockerized/7-days-to-die/Dockerfile" "steam-base"
emit "project-zomboid" "dockerized/project-zomboid" "dockerized/project-zomboid/Dockerfile" "steam-base"
emit "terraria" "dockerized/terraria" "dockerized/terraria/Dockerfile" "steam-base"
emit "l4d2" "dockerized/l4d2" "dockerized/l4d2/Dockerfile" "steam-base"
emit "insurgency-source" "dockerized/insurgency-source" "dockerized/insurgency-source/Dockerfile" "steam-base"
emit "insurgency-sandstorm" "dockerized/insurgency-sandstorm" "dockerized/insurgency-sandstorm/Dockerfile" "steam-base"
emit "cs-source" "dockerized/cs-source" "dockerized/cs-source/Dockerfile" "steam-base"
emit "kf2" "dockerized/kf2" "dockerized/kf2/Dockerfile" "steam-base"
emit "icarus" "dockerized/icarus" "dockerized/icarus/Dockerfile" "steam-base"
emit "the-forest" "dockerized/the-forest" "dockerized/the-forest/Dockerfile" "steam-base"
emit "sons-of-the-forest" "dockerized/sons-of-the-forest" "dockerized/sons-of-the-forest/Dockerfile" "steam-base"
emit "sniper-elite-4" "dockerized/sniper-elite-4" "dockerized/sniper-elite-4/Dockerfile" "steam-base"
emit "palworld" "dockerized/palworld" "dockerized/palworld/Dockerfile" "steam-base"
emit "starbound" "dockerized/starbound" "dockerized/starbound/Dockerfile" "steam-base"
emit "longvinter" "dockerized/longvinter" "dockerized/longvinter/Dockerfile" "steam-base"
emit "barotrauma" "dockerized/barotrauma" "dockerized/barotrauma/Dockerfile" "steam-base"
emit "unturned" "dockerized/unturned" "dockerized/unturned/Dockerfile" "steam-base"
emit "tf2" "dockerized/tf2" "dockerized/tf2/Dockerfile" "steam-base"
emit "cs2" "dockerized/cs2" "dockerized/cs2/Dockerfile" "steam-base"
emit "dod-source" "dockerized/dod-source" "dockerized/dod-source/Dockerfile" "steam-base"
emit "gmod" "dockerized/gmod" "dockerized/gmod/Dockerfile" "steam-base"
emit "delta-force-bhd" "dockerized/delta-force-bhd" "dockerized/delta-force-bhd/Dockerfile" "steam-base"
emit "dont-starve-together" "dockerized/dont-starve-together" "dockerized/dont-starve-together/Dockerfile" "steam-base"
emit "v-rising" "dockerized/v-rising" "dockerized/v-rising/Dockerfile" "steam-base"
emit "enshrouded" "dockerized/enshrouded" "dockerized/enshrouded/Dockerfile" "steam-base"
emit "satisfactory" "dockerized/satisfactory" "dockerized/satisfactory/Dockerfile" "steam-base"
emit "windrose" "dockerized/windrose" "dockerized/windrose/Dockerfile" "steam-base"
emit "vein" "dockerized/vein" "dockerized/vein/Dockerfile" "steam-base"
emit "arma-3" "dockerized" "dockerized/arma/arma-3/Dockerfile" "steam-base"
emit "arma-reforger" "dockerized/arma/reforger" "dockerized/arma/reforger/Dockerfile" "steam-base"
emit "dayz" "dockerized/dayz" "dockerized/dayz/Dockerfile" "steam-base"

emit "factorio" "dockerized/factorio" "dockerized/factorio/Dockerfile" "runtime-base"
emit "openmohaa" "dockerized/openmohaa" "dockerized/openmohaa/Dockerfile" "runtime-base"
emit "bf1942" "dockerized/bf1942" "dockerized/bf1942/Dockerfile" "runtime-base"
emit "bfv" "dockerized/bfv" "dockerized/bfv/Dockerfile" "runtime-base"
emit "cod" "dockerized/cod" "dockerized/cod/Dockerfile" "runtime-base"
emit "cod2" "dockerized/cod2" "dockerized/cod2/Dockerfile" "runtime-base"
emit "codwaw" "dockerized/codwaw" "dockerized/codwaw/Dockerfile" "runtime-base"
emit "cod4" "dockerized/cod4" "dockerized/cod4/Dockerfile" "runtime-base"
emit "quake3" "dockerized/quake3" "dockerized/quake3/Dockerfile" "runtime-base"
emit "rtcw" "dockerized/rtcw" "dockerized/rtcw/Dockerfile" "runtime-base"
emit "etl" "dockerized/etl" "dockerized/etl/Dockerfile" "runtime-base"
emit "supertuxkart" "dockerized/supertuxkart" "dockerized/supertuxkart/Dockerfile" "runtime-base"
emit "eco" "dockerized/eco" "dockerized/eco/Dockerfile" "steam-base"
