#!/bin/sh
# Resolve image matrix rows for CI.
# Prints one TSV line per image: name context dockerfile base_name_or_empty

set -eu

emit() {
  name="$1"
  context="$2"
  dockerfile="$3"
  base="${4:-}"
  printf '%s\t%s\t%s\t%s\n' "${name}" "${context}" "${dockerfile}" "${base}"
}

emit "minecraft-base" "bases/minecraft" "bases/minecraft/Dockerfile" ""
emit "steam-base" "bases/steam" "bases/steam/Dockerfile" ""
emit "runtime-base" "bases/runtime" "bases/runtime/Dockerfile" ""

emit "minecraft-fabric" "minecraft" "minecraft/fabric/Dockerfile" "minecraft-base"
emit "minecraft-vanilla" "minecraft" "minecraft/vanilla/Dockerfile" "minecraft-base"
emit "minecraft-forge" "minecraft" "minecraft/forge/Dockerfile" "minecraft-base"
emit "minecraft-neoforge" "minecraft" "minecraft/neoforge/Dockerfile" "minecraft-base"

emit "valheim" "valheim/vanilla" "valheim/vanilla/Dockerfile" "steam-base"
emit "valheim-plus" "valheim/plus" "valheim/plus/Dockerfile" "steam-base"
emit "ground-branch" "ground-branch" "ground-branch/Dockerfile" "steam-base"
emit "space-engineers" "space-engineers" "space-engineers/Dockerfile" "steam-base"
emit "core-keeper" "core-keeper" "core-keeper/Dockerfile" "steam-base"
emit "7-days-to-die" "7-days-to-die" "7-days-to-die/Dockerfile" "steam-base"
emit "project-zomboid" "project-zomboid" "project-zomboid/Dockerfile" "steam-base"
emit "terraria" "terraria" "terraria/Dockerfile" "steam-base"
emit "l4d2" "l4d2" "l4d2/Dockerfile" "steam-base"
emit "insurgency-source" "insurgency-source" "insurgency-source/Dockerfile" "steam-base"
emit "insurgency-sandstorm" "insurgency-sandstorm" "insurgency-sandstorm/Dockerfile" "steam-base"
emit "cs-source" "cs-source" "cs-source/Dockerfile" "steam-base"
emit "kf2" "kf2" "kf2/Dockerfile" "steam-base"
emit "icarus" "icarus" "icarus/Dockerfile" "steam-base"
emit "the-forest" "the-forest" "the-forest/Dockerfile" "steam-base"
emit "sons-of-the-forest" "sons-of-the-forest" "sons-of-the-forest/Dockerfile" "steam-base"
emit "sniper-elite-4" "sniper-elite-4" "sniper-elite-4/Dockerfile" "steam-base"
emit "palworld" "palworld" "palworld/Dockerfile" "steam-base"
emit "starbound" "starbound" "starbound/Dockerfile" "steam-base"
emit "longvinter" "longvinter" "longvinter/Dockerfile" "steam-base"
emit "barotrauma" "barotrauma" "barotrauma/Dockerfile" "steam-base"
emit "unturned" "unturned" "unturned/Dockerfile" "steam-base"
emit "tf2" "tf2" "tf2/Dockerfile" "steam-base"
emit "cs2" "cs2" "cs2/Dockerfile" "steam-base"
emit "dod-source" "dod-source" "dod-source/Dockerfile" "steam-base"
emit "gmod" "gmod" "gmod/Dockerfile" "steam-base"
emit "delta-force-bhd" "delta-force-bhd" "delta-force-bhd/Dockerfile" "steam-base"
emit "arma-3" "arma/arma-3" "arma/arma-3/Dockerfile" "steam-base"
emit "arma-reforger" "arma/reforger" "arma/reforger/Dockerfile" "steam-base"
emit "dayz" "dayz" "dayz/Dockerfile" "steam-base"

emit "factorio" "factorio" "factorio/Dockerfile" "runtime-base"
emit "openmohaa" "openmohaa" "openmohaa/Dockerfile" "runtime-base"
emit "bf1942" "bf1942" "bf1942/Dockerfile" "runtime-base"
emit "bfv" "bfv" "bfv/Dockerfile" "runtime-base"
emit "cod" "cod" "cod/Dockerfile" "runtime-base"
emit "cod2" "cod2" "cod2/Dockerfile" "runtime-base"
emit "codwaw" "codwaw" "codwaw/Dockerfile" "runtime-base"
emit "cod4" "cod4" "cod4/Dockerfile" "runtime-base"
emit "quake3" "quake3" "quake3/Dockerfile" "runtime-base"
emit "rtcw" "rtcw" "rtcw/Dockerfile" "runtime-base"
emit "etl" "etl" "etl/Dockerfile" "runtime-base"
emit "supertuxkart" "supertuxkart" "supertuxkart/Dockerfile" "runtime-base"
emit "eco" "eco" "eco/Dockerfile" "steam-base"
